// Marrakech neighborhoods
const marrakechNeighborhoods = [
	{ value: "bab-doukkala", label: "Bab Doukkala Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "sidi-mimoun", label: "Sidi Mimoun Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "kasbah", label: "Kasbah Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "el-ksour", label: "El Ksour Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "berrima", label: "Berrima Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "riad-zitoun-jdid", label: "Riad Zitoun Jdid Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "riad-zitoun-lakdim", label: "Riad Zitoun Lakdim Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "riad-laarous", label: "Riad Laarous Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "mouassine", label: "Mouassine Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "bab-taghzout", label: "Bab Taghzout Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "bab-kechich", label: "Bab Kechich Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "ben-salah", label: "Ben Salah Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "derb-dabachi", label: "Derb Dabachi Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "derb-sidi-bouamar", label: "Derb Sidi Bouamar Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "derb-el-maaza", label: "Derb el Maâza Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "derb-el-kadi", label: "Derb el Kadi Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "derb-aghrab", label: "Derb Aghrab Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "derb-el-ferrane", label: "Derb el Ferrane Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "kennaria", label: "Kennaria Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "lakssour", label: "Lakssour Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "sidi-abdellaziz", label: "Sidi Abdellaziz Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "souk-semmarine", label: "Souk Semmarine Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "jemaa-el-fna", label: "Jemaa el Fna Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "mellah", label: "Mellah Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-essalam", label: "Hay Essalam Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-salam", label: "Hay Salam Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-el-bahroura", label: "Hay El Bahroura Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "bab-ahmar", label: "Bab Ahmar Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "bab-aylan", label: "Bab Aylan Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "bab-hmar", label: "Bab Hmar Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "bab-khemis", label: "Bab Khemis Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "gueliz-centre", label: "Guéliz Centre Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "camp-el-ghoul", label: "Camp El Ghoul Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "majorelle", label: "Majorelle Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "diour-saboun", label: "Diour Saboun Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "semlalia", label: "Semlalia Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "rue-de-yougoslavie", label: "Rue de Yougoslavie Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "avenue-abdelkarim-khattabi", label: "Avenue Abdelkarim Khattabi Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "zerktouni", label: "Zerktouni Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "ibn-tachfine", label: "Ibn Tachfine Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "afaq", label: "Afaq Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "arset-aouzal-extension", label: "Arset Aouzal Extension Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "daoudiate-south", label: "Daoudiate South Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "douar-laskar", label: "Douar Laskar Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-sakar", label: "Hay Sakar Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "massira-khadra", label: "Massira Khadra Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hivernage-nord", label: "Hivernage Nord Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hivernage-sud", label: "Hivernage Sud Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "avenue-mohamed-vi-zone", label: "Avenue Mohamed VI Zone Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "menara-gardens-zone", label: "Menara Gardens Zone Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "quartier-du-theatre-royal", label: "Quartier du Théâtre Royal Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "agdal", label: "Agdal Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "aguedal-gardens", label: "Aguedal Gardens Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "avenue-de-la-menara", label: "Avenue de la Ménara Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "avenue-hassan-ii-extension", label: "Avenue Hassan II Extension Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "el-harti", label: "El Harti Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "mhamid-shared-zone", label: "Mhamid Shared Zone Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "massira-i", label: "Massira I Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "massira-ii", label: "Massira II Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "massira-iii", label: "Massira III Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-oumnas", label: "Hay Oumnas Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-menara", label: "Hay Menara Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "sidi-abbad", label: "Sidi Abbad Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-al-farah", label: "Hay Al Farah Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-el-hana", label: "Hay El Hana Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "syba-centre", label: "SYBA Centre Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "el-baraka", label: "El Baraka Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "riad-zitoun-syba", label: "Riad Zitoun SYBA Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "riad-el-atlas", label: "Riad El Atlas Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "sidi-youssef-el-gharbi", label: "Sidi Youssef El Gharbi Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "sidi-youssef-el-cherqi", label: "Sidi Youssef El Cherqi Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "douar-el-qods", label: "Douar El Qods Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-el-inara", label: "Hay El Inara Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-mohammadi", label: "Hay Mohammadi Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "jnane-awrad", label: "Jnane Awrad Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "arset-tihiri", label: "Arset Tihiri Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-jnane-houara", label: "Hay Jnane Houara Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-saada", label: "Hay Saada Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-el-mhammedia", label: "Hay El Mhammedia Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "palmeraie-1", label: "Palmeraie 1 Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "palmeraie-2", label: "Palmeraie 2 Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "palmeraie-3", label: "Palmeraie 3 Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "dar-tounsi", label: "Dar Tounsi Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "ennakhil-nord", label: "Ennakhil Nord Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "ennakhil-sud", label: "Ennakhil Sud Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "nabou", label: "Nabou Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "oulad-hassoun", label: "Oulad Hassoun Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "ghabat-chrifia", label: "Ghabat Chrifia Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "douar-abiad", label: "Douar Abiad Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "douar-ben-rahmoune", label: "Douar Ben Rahmoune Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "bab-atlas", label: "Bab Atlas Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "circuit-de-la-palmeraie", label: "Circuit de la Palmeraie Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "douar-lahna", label: "Douar Lahna Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "douar-laarassi", label: "Douar Laarassi Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "ouled-moumen", label: "Ouled Moumen Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "targa-oulad-azzouz", label: "Targa Oulad Azzouz Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "targa-nakhil", label: "Targa Nakhil Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "targa-lalla-haya", label: "Targa Lalla Haya Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "targa-wahat", label: "Targa Wahat Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "targa-campagne", label: "Targa Campagne Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-al-wifaq", label: "Hay Al Wifaq Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-riad-targa", label: "Hay Riad Targa Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "yasmine-targa", label: "Yasmine Targa Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "jawhara-targa", label: "Jawhara Targa Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "manzah-targa", label: "Manzah Targa Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "mhamid-1", label: "Mhamid 1 Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "mhamid-2", label: "Mhamid 2 Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "mhamid-3", label: "Mhamid 3 Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "mhamid-4", label: "Mhamid 4 Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "mhamid-5", label: "Mhamid 5 Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "mhamid-6", label: "Mhamid 6 Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "mhamid-7", label: "Mhamid 7 Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "mhamid-8", label: "Mhamid 8 Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "mhamid-9", label: "Mhamid 9 Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-nassim", label: "Hay Nassim Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-massira-azli", label: "Hay Massira Azli Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-el-bassatine", label: "Hay El Bassatine Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-el-fath", label: "Hay El Fath Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-el-moustakbal", label: "Hay El Moustakbal Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "daoudiate", label: "Daoudiate Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "daoudiate-est", label: "Daoudiate Est Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "daoudiate-ouest", label: "Daoudiate Ouest Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-el-mhamid-extension", label: "Hay El Mhamid Extension Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "sidi-ghanem-industriel", label: "Sidi Ghanem Industriel Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "jnane-al-atiq", label: "Jnane Al Atiq Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "lotissement-mabrouka", label: "Lotissement Mabrouka Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "mawarid", label: "Mawarid Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-el-addarissa", label: "Hay El Addarissa Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-el-ousra", label: "Hay El Ousra Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-el-rahma", label: "Hay El Rahma Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "massira-1", label: "Massira 1 Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "massira-2", label: "Massira 2 Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "massira-3", label: "Massira 3 Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "massira-4", label: "Massira 4 Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-azli", label: "Hay Azli Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-al-hassania", label: "Hay Al Hassania Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-al-amal", label: "Hay Al Amal Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-al-jadid", label: "Hay Al Jadid Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-chrifia", label: "Hay Chrifia Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "hay-dabachi-extension", label: "Hay Dabachi Extension Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "sidi-ghanem-centre", label: "Sidi Ghanem Centre Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "sidi-ghanem-nord", label: "Sidi Ghanem Nord Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "sidi-ghanem-sud", label: "Sidi Ghanem Sud Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "zone-industrielle-1", label: "Zone Industrielle 1 Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "zone-industrielle-2", label: "Zone Industrielle 2 Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "magasin-ar-zone", label: "Magasin AR Zone Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "diour-sidi-ghanem-lotissements", label: "Diour Sidi Ghanem Lotissements Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "tamansourt", label: "Tamansourt Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "chwiter", label: "Chwiter Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "tassoultante", label: "Tassoultante Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "ait-ourir-road-zone", label: "Ait Ourir Road Zone Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "douar-sidi-moussa", label: "Douar Sidi Moussa Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "ouled-dlim", label: "Ouled Dlim Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "el-atabi", label: "El Atabi Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "el-warda", label: "El Warda Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "el-ouidane", label: "El Ouidane Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "oulad-merzoug", label: "Oulad Merzoug Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "issil", label: "Issil Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "complexe-issil-area", label: "Complexe Issil Area Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "jnane-issil", label: "Jnane Issil Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
	{ value: "residence-issil-extension", label: "Résidence Issil Extension Marrakech", flag: "🇲🇦", latlng: [31.6295, -7.9811], region: "Marrakech" },
];

const useCountries = () => {
	const getAll = () => marrakechNeighborhoods;

	const getByValue = (value) => {
		return marrakechNeighborhoods.find((item) => item.value === value);
	};

	return {
		getAll,
		getByValue,
	};
};

export default useCountries;
