// Moroccan Cities with their neighborhoods and coordinates
export const moroccanCities = [
	{
		value: "marrakech",
		label: "Marrakech",
		latlng: [31.6295, -7.9811],
		neighborhoods: [
			{ value: "bab-doukkala", label: "Bab Doukkala" },
			{ value: "sidi-mimoun", label: "Sidi Mimoun" },
			{ value: "kasbah", label: "Kasbah" },
			{ value: "el-ksour", label: "El Ksour" },
			{ value: "berrima", label: "Berrima" },
			{ value: "riad-zitoun-jdid", label: "Riad Zitoun Jdid" },
			{ value: "riad-zitoun-lakdim", label: "Riad Zitoun Lakdim" },
			{ value: "riad-laarous", label: "Riad Laarous" },
			{ value: "mouassine", label: "Mouassine" },
			{ value: "bab-taghzout", label: "Bab Taghzout" },
			{ value: "bab-kechich", label: "Bab Kechich" },
			{ value: "ben-salah", label: "Ben Salah" },
			{ value: "derb-dabachi", label: "Derb Dabachi" },
			{ value: "derb-sidi-bouamar", label: "Derb Sidi Bouamar" },
			{ value: "derb-el-maaza", label: "Derb el Maâza" },
			{ value: "derb-el-kadi", label: "Derb el Kadi" },
			{ value: "derb-aghrab", label: "Derb Aghrab" },
			{ value: "derb-el-ferrane", label: "Derb el Ferrane" },
			{ value: "kennaria", label: "Kennaria" },
			{ value: "lakssour", label: "Lakssour" },
			{ value: "sidi-abdellaziz", label: "Sidi Abdellaziz" },
			{ value: "souk-semmarine", label: "Souk Semmarine" },
			{ value: "jemaa-el-fna", label: "Jemaa el Fna" },
			{ value: "mellah", label: "Mellah" },
			{ value: "hay-essalam", label: "Hay Essalam" },
			{ value: "hay-salam", label: "Hay Salam" },
			{ value: "hay-el-bahroura", label: "Hay El Bahroura" },
			{ value: "bab-ahmar", label: "Bab Ahmar" },
			{ value: "bab-aylan", label: "Bab Aylan" },
			{ value: "bab-hmar", label: "Bab Hmar" },
			{ value: "bab-khemis", label: "Bab Khemis" },
			{ value: "gueliz-centre", label: "Guéliz Centre" },
			{ value: "camp-el-ghoul", label: "Camp El Ghoul" },
			{ value: "majorelle", label: "Majorelle" },
			{ value: "diour-saboun", label: "Diour Saboun" },
			{ value: "semlalia", label: "Semlalia" },
			{ value: "rue-de-yougoslavie", label: "Rue de Yougoslavie" },
			{ value: "avenue-abdelkarim-khattabi", label: "Avenue Abdelkarim Khattabi" },
			{ value: "zerktouni", label: "Zerktouni" },
			{ value: "ibn-tachfine", label: "Ibn Tachfine" },
			{ value: "afaq", label: "Afaq" },
			{ value: "arset-aouzal-extension", label: "Arset Aouzal Extension" },
			{ value: "daoudiate-south", label: "Daoudiate South" },
			{ value: "douar-laskar", label: "Douar Laskar" },
			{ value: "hay-sakar", label: "Hay Sakar" },
			{ value: "massira-khadra", label: "Massira Khadra" },
			{ value: "hivernage-nord", label: "Hivernage Nord" },
			{ value: "hivernage-sud", label: "Hivernage Sud" },
			{ value: "avenue-mohamed-vi-zone", label: "Avenue Mohamed VI Zone" },
			{ value: "menara-gardens-zone", label: "Menara Gardens Zone" },
			{ value: "quartier-du-theatre-royal", label: "Quartier du Théâtre Royal" },
			{ value: "agdal", label: "Agdal" },
			{ value: "aguedal-gardens", label: "Aguedal Gardens" },
			{ value: "avenue-de-la-menara", label: "Avenue de la Ménara" },
			{ value: "avenue-hassan-ii-extension", label: "Avenue Hassan II Extension" },
			{ value: "el-harti", label: "El Harti" },
			{ value: "mhamid-shared-zone", label: "Mhamid Shared Zone" },
			{ value: "massira-i", label: "Massira I" },
			{ value: "massira-ii", label: "Massira II" },
			{ value: "massira-iii", label: "Massira III" },
			{ value: "hay-oumnas", label: "Hay Oumnas" },
			{ value: "hay-menara", label: "Hay Menara" },
			{ value: "sidi-abbad", label: "Sidi Abbad" },
			{ value: "hay-al-farah", label: "Hay Al Farah" },
			{ value: "hay-el-hana", label: "Hay El Hana" },
			{ value: "syba-centre", label: "SYBA Centre" },
			{ value: "el-baraka", label: "El Baraka" },
			{ value: "riad-zitoun-syba", label: "Riad Zitoun SYBA" },
			{ value: "riad-el-atlas", label: "Riad El Atlas" },
			{ value: "sidi-youssef-el-gharbi", label: "Sidi Youssef El Gharbi" },
			{ value: "sidi-youssef-el-cherqi", label: "Sidi Youssef El Cherqi" },
			{ value: "douar-el-qods", label: "Douar El Qods" },
			{ value: "hay-el-inara", label: "Hay El Inara" },
			{ value: "hay-mohammadi", label: "Hay Mohammadi" },
			{ value: "jnane-awrad", label: "Jnane Awrad" },
			{ value: "arset-tihiri", label: "Arset Tihiri" },
			{ value: "hay-jnane-houara", label: "Hay Jnane Houara" },
			{ value: "hay-saada", label: "Hay Saada" },
			{ value: "hay-el-mhammedia", label: "Hay El Mhammedia" },
			{ value: "palmeraie-1", label: "Palmeraie 1" },
			{ value: "palmeraie-2", label: "Palmeraie 2" },
			{ value: "palmeraie-3", label: "Palmeraie 3" },
			{ value: "dar-tounsi", label: "Dar Tounsi" },
			{ value: "ennakhil-nord", label: "Ennakhil Nord" },
			{ value: "ennakhil-sud", label: "Ennakhil Sud" },
			{ value: "nabou", label: "Nabou" },
			{ value: "oulad-hassoun", label: "Oulad Hassoun" },
			{ value: "ghabat-chrifia", label: "Ghabat Chrifia" },
			{ value: "douar-abiad", label: "Douar Abiad" },
			{ value: "douar-ben-rahmoune", label: "Douar Ben Rahmoune" },
			{ value: "bab-atlas", label: "Bab Atlas" },
			{ value: "circuit-de-la-palmeraie", label: "Circuit de la Palmeraie" },
			{ value: "douar-lahna", label: "Douar Lahna" },
			{ value: "douar-laarassi", label: "Douar Laarassi" },
			{ value: "ouled-moumen", label: "Ouled Moumen" },
			{ value: "targa-oulad-azzouz", label: "Targa Oulad Azzouz" },
			{ value: "targa-nakhil", label: "Targa Nakhil" },
			{ value: "targa-lalla-haya", label: "Targa Lalla Haya" },
			{ value: "targa-wahat", label: "Targa Wahat" },
			{ value: "targa-campagne", label: "Targa Campagne" },
			{ value: "hay-al-wifaq", label: "Hay Al Wifaq" },
			{ value: "hay-riad-targa", label: "Hay Riad Targa" },
			{ value: "yasmine-targa", label: "Yasmine Targa" },
			{ value: "jawhara-targa", label: "Jawhara Targa" },
			{ value: "manzah-targa", label: "Manzah Targa" },
			{ value: "mhamid-1", label: "Mhamid 1" },
			{ value: "mhamid-2", label: "Mhamid 2" },
			{ value: "mhamid-3", label: "Mhamid 3" },
			{ value: "mhamid-4", label: "Mhamid 4" },
			{ value: "mhamid-5", label: "Mhamid 5" },
			{ value: "mhamid-6", label: "Mhamid 6" },
			{ value: "mhamid-7", label: "Mhamid 7" },
			{ value: "mhamid-8", label: "Mhamid 8" },
			{ value: "mhamid-9", label: "Mhamid 9" },
			{ value: "hay-nassim", label: "Hay Nassim" },
			{ value: "hay-massira-azli", label: "Hay Massira Azli" },
			{ value: "hay-el-bassatine", label: "Hay El Bassatine" },
			{ value: "hay-el-fath", label: "Hay El Fath" },
			{ value: "hay-el-moustakbal", label: "Hay El Moustakbal" },
			{ value: "daoudiate", label: "Daoudiate" },
			{ value: "daoudiate-est", label: "Daoudiate Est" },
			{ value: "daoudiate-ouest", label: "Daoudiate Ouest" },
			{ value: "hay-el-mhamid-extension", label: "Hay El Mhamid Extension" },
			{ value: "sidi-ghanem-industriel", label: "Sidi Ghanem Industriel" },
			{ value: "jnane-al-atiq", label: "Jnane Al Atiq" },
			{ value: "lotissement-mabrouka", label: "Lotissement Mabrouka" },
			{ value: "mawarid", label: "Mawarid" },
			{ value: "hay-el-addarissa", label: "Hay El Addarissa" },
			{ value: "hay-el-ousra", label: "Hay El Ousra" },
			{ value: "hay-el-rahma", label: "Hay El Rahma" },
			{ value: "massira-1", label: "Massira 1" },
			{ value: "massira-2", label: "Massira 2" },
			{ value: "massira-3", label: "Massira 3" },
			{ value: "massira-4", label: "Massira 4" },
			{ value: "hay-azli", label: "Hay Azli" },
			{ value: "hay-al-hassania", label: "Hay Al Hassania" },
			{ value: "hay-al-amal", label: "Hay Al Amal" },
			{ value: "hay-al-jadid", label: "Hay Al Jadid" },
			{ value: "hay-chrifia", label: "Hay Chrifia" },
			{ value: "hay-dabachi-extension", label: "Hay Dabachi Extension" },
			{ value: "sidi-ghanem-centre", label: "Sidi Ghanem Centre" },
			{ value: "sidi-ghanem-nord", label: "Sidi Ghanem Nord" },
			{ value: "sidi-ghanem-sud", label: "Sidi Ghanem Sud" },
			{ value: "zone-industrielle-1", label: "Zone Industrielle 1" },
			{ value: "zone-industrielle-2", label: "Zone Industrielle 2" },
			{ value: "magasin-ar-zone", label: "Magasin AR Zone" },
			{ value: "diour-sidi-ghanem-lotissements", label: "Diour Sidi Ghanem Lotissements" },
			{ value: "tamansourt", label: "Tamansourt" },
			{ value: "chwiter", label: "Chwiter" },
			{ value: "tassoultante", label: "Tassoultante" },
			{ value: "ait-ourir-road-zone", label: "Ait Ourir Road Zone" },
			{ value: "douar-sidi-moussa", label: "Douar Sidi Moussa" },
			{ value: "ouled-dlim", label: "Ouled Dlim" },
			{ value: "el-atabi", label: "El Atabi" },
			{ value: "el-warda", label: "El Warda" },
			{ value: "el-ouidane", label: "El Ouidane" },
			{ value: "oulad-merzoug", label: "Oulad Merzoug" },
			{ value: "issil", label: "Issil" },
			{ value: "complexe-issil-area", label: "Complexe Issil Area" },
			{ value: "jnane-issil", label: "Jnane Issil" },
			{ value: "residence-issil-extension", label: "Résidence Issil Extension" },
		],
	},
	{
		value: "casablanca",
		label: "Casablanca",
		latlng: [33.5731, -7.5898],
		neighborhoods: [
			{ value: "maarif", label: "Maarif" },
			{ value: "gauthier", label: "Gauthier" },
			{ value: "anfa", label: "Anfa" },
			{ value: "bourgogne", label: "Bourgogne" },
			{ value: "racine", label: "Racine" },
			{ value: "hay-riad", label: "Hay Riad" },
			{ value: "ain-diab", label: "Ain Diab" },
			{ value: "corniche", label: "Corniche" },
			{ value: "sidi-maarouf", label: "Sidi Maarouf" },
			{ value: "oasis", label: "Oasis" },
			{ value: "derb-sultan", label: "Derb Sultan" },
			{ value: "hay-mohammadi", label: "Hay Mohammadi" },
			{ value: "ain-sebaa", label: "Ain Sebaa" },
			{ value: "sidi-bernoussi", label: "Sidi Bernoussi" },
			{ value: "hay-hassani", label: "Hay Hassani" },
			{ value: "mohammedia", label: "Mohammedia" },
		],
	},
	{
		value: "rabat",
		label: "Rabat",
		latlng: [34.0209, -6.8416],
		neighborhoods: [
			{ value: "agdal", label: "Agdal" },
			{ value: "hay-riad", label: "Hay Riad" },
			{ value: "souissi", label: "Souissi" },
			{ value: "hay-ryad", label: "Hay Ryad" },
			{ value: "hay-fath", label: "Hay Fath" },
			{ value: "akrach", label: "Akrach" },
			{ value: "temara", label: "Temara" },
			{ value: "hay-nahda", label: "Hay Nahda" },
			{ value: "hay-ennasr", label: "Hay Ennasr" },
			{ value: "medina", label: "Medina" },
			{ value: "kasbah-des-oudayas", label: "Kasbah des Oudayas" },
			{ value: "hay-essalam", label: "Hay Essalam" },
		],
	},
	{
		value: "fes",
		label: "Fes",
		latlng: [34.0331, -5.0003],
		neighborhoods: [
			{ value: "fes-el-bali", label: "Fes El Bali" },
			{ value: "fes-el-jdid", label: "Fes El Jdid" },
			{ value: "ville-nouvelle", label: "Ville Nouvelle" },
			{ value: "hay-riad", label: "Hay Riad" },
			{ value: "ain-chkef", label: "Ain Chkef" },
			{ value: "saiss", label: "Saiss" },
			{ value: "hay-ennasr", label: "Hay Ennasr" },
			{ value: "hay-essalam", label: "Hay Essalam" },
			{ value: "hay-moulay-abdallah", label: "Hay Moulay Abdallah" },
		],
	},
	{
		value: "tangier",
		label: "Tangier",
		latlng: [35.7595, -5.8339],
		neighborhoods: [
			{ value: "medina", label: "Medina" },
			{ value: "kasbah", label: "Kasbah" },
			{ value: "marshan", label: "Marshan" },
			{ value: "boukhalef", label: "Boukhalef" },
			{ value: "hay-riad", label: "Hay Riad" },
			{ value: "hay-ennasr", label: "Hay Ennasr" },
			{ value: "hay-mghogha", label: "Hay Mghogha" },
			{ value: "charf", label: "Charf" },
			{ value: "beni-makada", label: "Beni Makada" },
		],
	},
	{
		value: "agadir",
		label: "Agadir",
		latlng: [30.4278, -9.5981],
		neighborhoods: [
			{ value: "hay-mohammadi", label: "Hay Mohammadi" },
			{ value: "hay-riad", label: "Hay Riad" },
			{ value: "hay-ennasr", label: "Hay Ennasr" },
			{ value: "hay-salam", label: "Hay Salam" },
			{ value: "talborjt", label: "Talborjt" },
			{ value: "ibn-zohr", label: "Ibn Zohr" },
			{ value: "hay-adrar", label: "Hay Adrar" },
			{ value: "anza", label: "Anza" },
		],
	},
	{
		value: "meknes",
		label: "Meknes",
		latlng: [33.8950, -5.5547],
		neighborhoods: [
			{ value: "medina", label: "Medina" },
			{ value: "hay-riad", label: "Hay Riad" },
			{ value: "hay-ennasr", label: "Hay Ennasr" },
			{ value: "agdal", label: "Agdal" },
			{ value: "borj-moulay-omar", label: "Borj Moulay Omar" },
			{ value: "hay-essalam", label: "Hay Essalam" },
		],
	},
	{
		value: "oujda",
		label: "Oujda",
		latlng: [34.6867, -1.9114],
		neighborhoods: [
			{ value: "medina", label: "Medina" },
			{ value: "hay-riad", label: "Hay Riad" },
			{ value: "hay-ennasr", label: "Hay Ennasr" },
			{ value: "hay-essalam", label: "Hay Essalam" },
			{ value: "hay-al-quods", label: "Hay Al Quods" },
		],
	},
	{
		value: "kenitra",
		label: "Kenitra",
		latlng: [34.2611, -6.5802],
		neighborhoods: [
			{ value: "medina", label: "Medina" },
			{ value: "hay-riad", label: "Hay Riad" },
			{ value: "hay-ennasr", label: "Hay Ennasr" },
			{ value: "hay-essalam", label: "Hay Essalam" },
			{ value: "mehdia", label: "Mehdia" },
		],
	},
	{
		value: "tetouan",
		label: "Tetouan",
		latlng: [35.5769, -5.3684],
		neighborhoods: [
			{ value: "medina", label: "Medina" },
			{ value: "hay-riad", label: "Hay Riad" },
			{ value: "hay-ennasr", label: "Hay Ennasr" },
			{ value: "hay-essalam", label: "Hay Essalam" },
			{ value: "martil", label: "Martil" },
		],
	},
	{
		value: "safi",
		label: "Safi",
		latlng: [32.2989, -9.2377],
		neighborhoods: [
			{ value: "medina", label: "Medina" },
			{ value: "hay-riad", label: "Hay Riad" },
			{ value: "hay-ennasr", label: "Hay Ennasr" },
			{ value: "hay-essalam", label: "Hay Essalam" },
		],
	},
	{
		value: "el-jadida",
		label: "El Jadida",
		latlng: [33.2316, -8.5007],
		neighborhoods: [
			{ value: "medina", label: "Medina" },
			{ value: "hay-riad", label: "Hay Riad" },
			{ value: "hay-ennasr", label: "Hay Ennasr" },
			{ value: "hay-essalam", label: "Hay Essalam" },
		],
	},
	{
		value: "beni-mellal",
		label: "Beni Mellal",
		latlng: [32.3373, -6.3498],
		neighborhoods: [
			{ value: "medina", label: "Medina" },
			{ value: "hay-riad", label: "Hay Riad" },
			{ value: "hay-ennasr", label: "Hay Ennasr" },
			{ value: "hay-essalam", label: "Hay Essalam" },
		],
	},
	{
		value: "taza",
		label: "Taza",
		latlng: [34.2139, -4.0086],
		neighborhoods: [
			{ value: "medina", label: "Medina" },
			{ value: "hay-riad", label: "Hay Riad" },
			{ value: "hay-ennasr", label: "Hay Ennasr" },
			{ value: "hay-essalam", label: "Hay Essalam" },
		],
	},
	{
		value: "nador",
		label: "Nador",
		latlng: [35.1681, -2.9336],
		neighborhoods: [
			{ value: "medina", label: "Medina" },
			{ value: "hay-riad", label: "Hay Riad" },
			{ value: "hay-ennasr", label: "Hay Ennasr" },
			{ value: "hay-essalam", label: "Hay Essalam" },
		],
	},
	{
		value: "settat",
		label: "Settat",
		latlng: [33.0017, -7.6167],
		neighborhoods: [
			{ value: "medina", label: "Medina" },
			{ value: "hay-riad", label: "Hay Riad" },
			{ value: "hay-ennasr", label: "Hay Ennasr" },
			{ value: "hay-essalam", label: "Hay Essalam" },
		],
	},
	{
		value: "larache",
		label: "Larache",
		latlng: [35.1939, -6.1556],
		neighborhoods: [
			{ value: "medina", label: "Medina" },
			{ value: "hay-riad", label: "Hay Riad" },
			{ value: "hay-ennasr", label: "Hay Ennasr" },
			{ value: "hay-essalam", label: "Hay Essalam" },
		],
	},
	{
		value: "khouribga",
		label: "Khouribga",
		latlng: [32.8847, -6.9061],
		neighborhoods: [
			{ value: "medina", label: "Medina" },
			{ value: "hay-riad", label: "Hay Riad" },
			{ value: "hay-ennasr", label: "Hay Ennasr" },
			{ value: "hay-essalam", label: "Hay Essalam" },
		],
	},
	{
		value: "berkane",
		label: "Berkane",
		latlng: [34.9211, -2.3197],
		neighborhoods: [
			{ value: "medina", label: "Medina" },
			{ value: "hay-riad", label: "Hay Riad" },
			{ value: "hay-ennasr", label: "Hay Ennasr" },
			{ value: "hay-essalam", label: "Hay Essalam" },
		],
	},
	{
		value: "taourirt",
		label: "Taourirt",
		latlng: [34.4078, -2.8972],
		neighborhoods: [
			{ value: "medina", label: "Medina" },
			{ value: "hay-riad", label: "Hay Riad" },
			{ value: "hay-ennasr", label: "Hay Ennasr" },
			{ value: "hay-essalam", label: "Hay Essalam" },
		],
	},
	{
		value: "sidi-kacem",
		label: "Sidi Kacem",
		latlng: [34.2261, -5.7075],
		neighborhoods: [
			{ value: "medina", label: "Medina" },
			{ value: "hay-riad", label: "Hay Riad" },
			{ value: "hay-ennasr", label: "Hay Ennasr" },
			{ value: "hay-essalam", label: "Hay Essalam" },
		],
	},
	{
		value: "errachidia",
		label: "Errachidia",
		latlng: [31.9319, -4.4244],
		neighborhoods: [
			{ value: "medina", label: "Medina" },
			{ value: "hay-riad", label: "Hay Riad" },
			{ value: "hay-ennasr", label: "Hay Ennasr" },
			{ value: "hay-essalam", label: "Hay Essalam" },
		],
	},
];

// Helper function to get city by value
export const getCityByValue = (value) => {
	return moroccanCities.find((city) => city.value === value);
};

// Helper function to get neighborhoods by city value
export const getNeighborhoodsByCity = (cityValue) => {
	const city = getCityByValue(cityValue);
	return city ? city.neighborhoods : [];
};

// Helper function to format location value
export const formatLocationValue = (city, neighborhood) => {
	if (!city) return "";
	if (!neighborhood) return city.label;
	return `${neighborhood.label}, ${city.label}`;
};

